sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.3
  - 2.2
before_script:
  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - chmod 600 ~/.ssh/authorized_keys
